### ISSUE TITLE
Game crashes upon entering a singleplayer world

### ISSUE THREAD

**Issue by ooooggll** [Minigeee/life-crystals#2]
When creating a singleplayer world or joining a preexisting one with this mod installed, the game crashes.
The only mods installed are Fabric API and Life Crystals.

Crash report:
`
[18:10:47] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.6
[18:10:47] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[18:10:47] [main/INFO]: Loading 56 mods:
	- fabric-api 0.96.1+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.49+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.13+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.1+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.1+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.0+44c0f8c64f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.74+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.23+78d798af4f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.7+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.63+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.11+06274a474f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.18+78d798af4f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.53+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.0+d74054c14f
	   |-- fabric-rendering-v0 1.1.56+df3654b34f
	   |-- fabric-rendering-v1 3.2.0+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.18+b66dcf784f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.10+e84342304f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabricloader 0.15.6
	   \-- mixinextras 0.3.2
	- java 17
	- life-crystals 1.0.1
	- minecraft 1.20.4
[18:10:48] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/MYNAME/AppData/Roaming/com.modrinth.theseus/meta/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[18:10:51] [main/INFO]: Compatibility level set to JAVA_17
[18:10:52] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[18:10:56] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 132 milliseconds
[18:10:58] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[18:10:59] [Render thread/INFO]: Setting user: {MINECRAFT_USERNAME}
[18:10:59] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[18:11:00] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[18:11:01] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, life-crystals
[18:11:01] [Worker-Main-5/INFO]: Found unifont_all_no_pua-15.1.04.hex, loading
[18:11:02] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[18:11:02] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[18:11:03] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (Realtek(R) Audio)
[18:11:03] [Render thread/INFO]: Sound engine started
[18:11:03] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[18:11:03] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[18:11:03] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[18:11:03] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[18:11:03] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[18:11:03] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[18:11:03] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[18:11:03] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[18:11:03] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[18:11:03] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[18:11:03] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[18:11:03] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[18:11:03] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[18:11:03] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[18:11:14] [Render thread/INFO]: Loaded 7 recipes
[18:11:14] [Render thread/INFO]: Loaded 1271 advancements
[18:11:17] [Render thread/INFO]: Applied 3 biome modifications to 1 of 64 new biomes in 8.999 ms
[18:11:17] [Server thread/INFO]: Starting integrated minecraft server version 1.20.4
[18:11:17] [Server thread/INFO]: Generating keypair
[18:11:18] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[18:11:19] [Render thread/INFO]: Preparing spawn area: 0%
[18:11:19] [Render thread/INFO]: Preparing spawn area: 0%
[18:11:19] [Render thread/INFO]: Preparing spawn area: 22%
[18:11:20] [Render thread/INFO]: Preparing spawn area: 55%
[18:11:20] [Render thread/INFO]: Time elapsed: 1973 ms
[18:11:20] [Server thread/INFO]: Changing view distance to 12, from 10
[18:11:20] [Server thread/INFO]: Changing simulation distance to 12, from 0
[18:11:21] [Server thread/INFO]: {MINECRAFT_USERNAME}[local:E:5898a5d9] logged in with entity id 39 at (8.5, -60.0, -5.5)
[18:11:21] [Server thread/INFO]: {MINECRAFT_USERNAME} joined the game
[18:11:21] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'net.minecraft.class_18 net.minecraft.class_26.method_17924(java.util.function.Function, java.util.function.Supplier, java.lang.String)'
	at minigee.life_crystals.HealthState.getServerState(HealthState.java:62) ~[life-crystals-1.0.1.jar:?]
	at minigee.life_crystals.LifeCrystals.lambda$onInitialize$2(LifeCrystals.java:103) ~[life-crystals-1.0.1.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents.lambda$static$0(ServerEntityEvents.java:39) ~[fabric-lifecycle-events-v1-2.3.0+a67ffb5d4f-df781ed0de5bc62e.jar:?]
	at net.minecraft.class_3218$class_5526.handler$zep000$fabric-lifecycle-events-v1$invokeEntityLoadEvent(class_3218.java:1723) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1604) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1563) ~[client-intermediary.jar:?]
	at net.minecraft.class_5579.method_31847(class_5579.java:216) ~[client-intermediary.jar:?]
	at net.minecraft.class_5579.method_31820(class_5579.java:186) ~[client-intermediary.jar:?]
	at net.minecraft.class_5579.method_31818(class_5579.java:167) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18771(class_3218.java:924) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18213(class_3218.java:910) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:238) ~[client-intermediary.jar:?]
	at net.minecraft.class_8610.method_52408(class_8610.java:128) ~[client-intermediary.jar:?]
	at net.minecraft.class_8736.method_53043(class_8736.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_8736.method_11054(class_8736.java:7) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:797) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:779) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:773) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:687) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[18:11:21] [Server thread/ERROR]: This crash report has been saved to: C:\Users\MYNAME\AppData\Roaming\com.modrinth.theseus\profiles\test\crash-reports\crash-2024-02-17_18.11.21-server.txt
[18:11:21] [Server thread/INFO]: Stopping server
[18:11:21] [Server thread/INFO]: Saving players
[18:11:21] [Server thread/INFO]: Saving worlds
`

**Comment by Minigeee** [comment]
Thanks for pointing out the bug. Turns out the mod actually was only compatible with 1.20.1. But it should be fixed for version 1.20.4 and the new version should be up on Modrinth now. Please let me know if you continue running into issues.
